### ISSUE TITLE
Atualizar logo do site

### ISSUE THREAD

**Issue by endersonmenezes** [capitulomaringa/capitulomaringa.github.io#1]

**Comment by brunomioto** [comment]
![estandarte 2](https://user-images.githubusercontent.com/10459392/68886668-65ed6680-06f6-11ea-82fb-a548bb6ac85a.png)

**Comment by endersonmenezes** [comment]
https://github.com/capitulomaringa/capitulomaringa.github.io/commit/a3ac0ef950f2fee26a209461ed5557d6ac2cd0e3

Não editei a logo completa, apenas coloquei o simbolo e mandei pro ar :)
